# Load partials
file(READ ${BOOTSTRAP_FILE} BOOTSTRAP_CONTENTS)
file(READ ${STUBDUINO_SKETCH} SKETCH_CONTENTS)

# Compose bootstrap targe
file(WRITE ${BOOTSTRAP_SOURCE} "${BOOTSTRAP_CONTENTS}")
file(APPEND ${BOOTSTRAP_SOURCE} "${SKETCH_CONTENTS}")
